### PR TITLE
added "mentionSelect" input to allow selection formatting

### PR DESCRIPTION
**Pull request by taguan**
Fixed this issue : https://github.com/dmacfarlane/angular2-mentions/issues/13

### CODE REVIEW

**Comment by taguan** [comment]
Is it possible to merge this one (it is just adding a feature and doesn't hurt anything) and then to publish a new npm version ?
I need this and the offline compilation (which has already been merged) to be able to use this module in the project of my company.

**Comment by dmacfarlane** [comment]
Can you provide an example use-case for this? Why would the inserted text need to differ from the menu selection? Also, what value would be passed to the mentionSelect input?

**Comment by taguan** [comment]
Yes of course, I am actually already using it on a copied modified version of your project.
We allow the use to enter some variable we provide in some inputs and textarea. The variable is declared that way : {{myVariable}}.
The menu should propose the variable names when we hit '{', but when selected, it should enter {{the name}} instead of just "the name".

Example of code : 

```
<textarea class="form-control" id="templateText" [ngModel]="sink.formatter.templateText"
                  (ngModelChange)="formatterTemplateChanged($event)" rows="10"
                  [mention]="availableVariables | name" [triggerChar]="'{'" [mentionSelect]="variableFormatter" autocomplete="off">
```

with variableFormatter defined in the Component as : 

`variableFormatter: (variable: string) => string = (variable: string) => '{' + variable + '}}';`

**Comment by taguan** [comment]
Moreover, the mentio module from Angular1 you inspired from as the exact same functionality.

**Pull request merged**
