### PR TITLE
Included list templates that allows for complex mention lists

### PR DESCRIPTION
**Pull request by flore2003**
I've extended the library so that it uses templates for the list items, which allows for more complex items in the mention list, such as displaying the user's username or picture.

This actually also solves #30

### CODE REVIEW

**Comment by erikramalho** [comment]
Hey @dmacfarlane, what do think about merging it?

**Comment by erikramalho** [comment]
Hey @dmacfarlane, could you please review @flore2003 code and commit it? Pleeeeease!

**Comment by dmacfarlane** [comment]
This needs to be updated now that the async branch has been merged into master.

**Comment by erikramalho** [comment]
hey @flore2003! update your code. It seem @dmacfarlane is willing to merge your code!

**Comment by agarbund** [comment]
Hey @flore2003 thanks a lot for submitting this PR. I'm migrating app written in Angular 1.5 to Angular 4 and with this PR I'll be able to replace Ment.io from AngularJS. Any chance you'll have some time to fix these conflicts? If not, maybe I could help.

**Comment by flore2003** [comment]
I will look into it!

**Comment by flore2003** [comment]
@dmacfarlane I rebased my original work to the current state of the library (actually I improved it a little bit while doing so) and updated the pull request

@agarbund Would you be so kind to check my changes and tell me, if this solves your use case?

**Comment by flore2003** [comment]
@dmacfarlane I updated the pull request again to work with your latest changes.

**Comment by dmacfarlane** [comment]
I've merged this manually with a few minor changes in commit b13b77bab4a7ac4edc10cf93c23b47c8e77f1b49

Note there is a breaking change if the `mentionSelect` function was used. It was previously called with a string, and it will now be called with complex object.

**Pull request closed without merging**
