### PR TITLE
Fixed scrolling issues.

### PR DESCRIPTION
**Pull request by taguan**
Fixed scrolling issues. When pressing key up - key down, the box was not scrolling accordingly.
It meant then when hitting the key down more times than the number of initial visible items, the selected element was not visible anymore.

### CODE REVIEW

**Comment by dmacfarlane** [comment]
What browser/os are you seeing the scrolling issue on?

**Comment by taguan** [comment]
Chrome / Linux Mint

**Comment by dmacfarlane** [comment]
Should be fixed by a6c4182

**Comment by taguan** [comment]
You pointed a wrong commit (this one is just about the .gitignore), but I pulled master and tested the issue, it has indeed disappeared, and it seems to behave in a more styled way than my solution.

I close this pull request.

**Pull request closed without merging**
