### PR TITLE
Added ability to define a keycode as well as key value.

### PR DESCRIPTION
**Pull request by Tom-Hudson**
Changes as per my suggestion in #53

### CODE REVIEW

**Comment by Tom-Hudson** [comment]
@dmacfarlane - Is this PR being looked at? I notice there isn't much activity recently on this repo.

**Comment by dmacfarlane** [comment]
I'm hoping this can be fixed in Selenium to avoid adding additional config options to this package. I was also wondering if there was a straightforward way to get the keyCode from the triggerChar to avoid the config and provide a more universal solution, but that doesn't seem possible either.

**Comment by Tom-Hudson** [comment]
@dmacfarlane - agreed that Selenium should fix the issue. I took a look at it myself and it's quite a large job!

Would you accept my pull request instead if I change it so you can specify a keycode or key as the triggerChar?

**Key as triggerChar**
```
<input type="text" [mention]="items" [mentionConfig]="{triggerChar:'@',maxItems:10,labelKey:'name'}">
```
**KeyCode as triggerChar**
```
<input type="text" [mention]="items" [mentionConfig]="{triggerChar:192,maxItems:10,labelKey:'name'}">
```

I would then do a simple `typeOf` check so if the `triggerChar` is a number, then the keyCode is used, but if it's a string, the key will be used. I would obviously update the docs to reflect this. Let me know what you think!

**Comment by dmacfarlane** [comment]
If you leave the docs as they are (revert your change) and add the `typeof` check, I'll include it as a temporary (undocumented) fix until the issue with Selenium is fixed.

**Comment by Tom-Hudson** [comment]
@dmacfarlane - I have just implemented the change I suggested and have reverted all doc changes I made so this can go under the radar. Tested it locally with the e2e tests and they worked with the default, a specified char, and specifying a keyCode. It would be great if this could be released soon I can stop setting the keyboard config to US on our Selenium Server.

**Pull request merged**
